Task2
veraklim/Scala-complete-course pull request #2
Opened 2018-09-25 09:10 UTC by veraklim

2018-09-30 19:26 UTC, snwlnx requested changes

2018-09-30 19:26 UTC, snwlnx commented on src/main/scala/lectures/operators/Competition.scala
> +      case d: Double => d.toInt
- строго говоря не любую строку можно к инту преобразовать, но тут допустим будет так.

- что будет если на входе будет Long? (нужен какой-то общий паттерн)

2018-09-30 19:26 UTC, snwlnx commented on src/main/scala/lectures/functions/SQLAPI.scala
> +  def execute(sql: String) = ((logParameter[String]_ andThen ((connection compose logParameter[String]_)
лучше пистаь в одном стиле или andThen или compose,,
очень не читаемые преносы, 
попробуй писать каждую композицию с новой строки, пример:
```.andThen(...)
.andThen(...)
.andThen(...)
```

2018-10-08 08:33 UTC, sergeypopov83 commented on src/main/scala/lectures/operators/Competition.scala
> +      if (r._2>0) finalResult = finalResult + 1
следи, пожалуйста за стилем кода
В идее на win есть комбинация alt +ctl + L (на *nix системах комбинация может быть другой), которая форматирует код.

2018-10-12 12:56 UTC, sergeypopov83 commented on src/main/scala/lectures/operators/Competition.scala
> +  def toInt[T](a: T): Int = {
зачем так переусложнять 
выражения типа 
a match {
case i: Int => i
case c: Char => c.toInt
case d: Double if d.toInt == i  =>  
case _ => throw new Exception("bla  lba bla ")
}

2018-10-29 12:38 UTC, merged