Task4
veraklim/Scala-complete-course pull request #4
Opened 2018-10-08 10:20 UTC by veraklim

2018-10-14 20:25 UTC, snwlnx requested changes

2018-10-14 20:25 UTC, snwlnx commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    case Nil => data2
можно в матче использовать tuple от обоих листов, 
лучше не называть данные типа data1...n
здесь вполне напрашивается назвать left и right

2018-10-14 20:25 UTC, snwlnx commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +      case s: Some[Connection] => con
эта тоже самое что getOrlse или fold на опшене

2018-10-14 20:25 UTC, snwlnx commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +          Option(finRes) match {
вложенный паттерн матчинг не очень хороший паттерн,
здесь надо переписать, 
что-то вынести в отдельный метод и назвать его подходяще

2018-10-14 20:25 UTC, snwlnx commented on src/main/scala/lectures/collections/MyListImpl.scala
> +      case head :: Nil => f(acc, head)
ветка никогда не будет вызвана, 
Nil перекроется паттерном выше

2018-10-16 13:59 UTC, sergeypopov83 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        else merge(data1.tail, data2.head +: merge(Seq(data1.head), data2.tail))
Это вообще говоря не mergeSort) Алгоритм сильно смещен в сторону списков, частично отсортированных по возрастанию. Если на вход передать массив отсортированный в обратную сторону - это будет худший вариант и его сложность составит O(n^2).  Надо именно merge

2018-10-16 14:33 UTC, sergeypopov83 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def map(f: (Int) => Int) = this.flatMap(x => MyList(List(f(x))))
this не нужен

2018-10-16 14:33 UTC, sergeypopov83 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def foldLeft(acc: Int)(f: ((Int, Int) => Int)): Int = this.data match {
и здесь

2018-10-16 14:33 UTC, sergeypopov83 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +      case head :: tail => tail.foldLeft(f(acc, head))(f)
тут ты используешь  tail.foldLeft - это метод листа. Задача, реализовать foldLeft с использование только методов MyLIst

2018-10-29 12:47 UTC, sergeypopov83 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        if (data1.head <= data2.head) data1.head +: merge(data1.tail, data2)
Это не Tailrecursive реализация merge. Используй аккумулятор, что бы хранить отсортированные значения

2018-11-07 11:42 UTC, merged