Task5
veraklim/Scala-complete-course pull request #5
Opened 2018-10-09 10:00 UTC by veraklim

2018-10-14 20:28 UTC, snwlnx requested changes

2018-10-14 20:28 UTC, aliksz commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    def accum(acc: Int, couriers: List[Courier]): Int = couriers match {
паттерн матчинг тут нельзя использовать,
и здесь можно обойтись кратко только комбинаторами на списках,
не определяя своих функций

2018-11-07 12:03 UTC, sergeypopov83 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    val accum = couriers.filter(_ => traffic().degree < 5).foldLeft(0)((acc, i) =>
в оригинальном приложении цикл заканчивался, если все адреса были посещены (if trafficDegree < 5 && accum < addresses.length). В твоей реализации мы обходим всегда всех курьеров, даже если первый обслужил все адреса. Это надо исправить.  Смотри в сторону withFilter

2018-11-07 12:04 UTC, sergeypopov83 submitted a review, later dismissed

2018-11-07 12:06 UTC, sergeypopov83 requested changes

2018-11-07 12:06 UTC, sergeypopov83 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    val accum = couriers.filter(_ => traffic().degree < 5).foldLeft(0)((acc, i) =>
в оригинальном приложении цикл заканчивался, если все адреса были посещены (if trafficDegree < 5 && accum < addresses.length). В твоей реализации мы обходим всегда всех курьеров, даже если первый обслужил все адреса. Это надо исправить. Смотри в сторону withFilter

2018-12-19 17:51 UTC, merged